server:
  port: 0

spring:
  rabbitmq:
    host:  # 主机名
    port:  # 端口
    virtual-host:  # 虚拟主机
    username:  # 用户名
    password:  # 密码
    cache:
      channel:
        checkout-timeout: 3000000
    template:
      receive-timeout: 3000000
    listener:
      simple:
        prefetch: 1
